set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @resurrect-processes 'ssh vim'
# set -g @resurrect-save 'on'
# set -g @resurrect-restore 'on'

run-shell '~/.tmux/tmux-resurrect/resurrect.tmux'
run-shell '~/.tmux/plugins/tpm/tpm'
